### ISSUE TITLE
沒有辨法 run 起來 Error: Cannot find module 'readable-stream/transform'

### ISSUE THREAD

**Issue by wahengchang** [leancloud/LeanEngine-Full-Stack#23]
完成 
install npm 
install bower
avoscloud

但沒有辨法 run 起來 Error: Cannot find module 'readable-stream/transform'

**Comment by wangxiao** [comment]
确保 Nodejs 版本为 0.12

**Comment by wangxiao** [comment]
另外，仔细看下文档，你需要执行：
npm install
bower install
分别安装不同的依赖。
