### ISSUE TITLE
为什么在部署到云时报错

### ISSUE THREAD

**Issue by jasondu** [leancloud/LeanEngine-Full-Stack#28]
部署的时候报这个错，这是为什么呢？步骤都按你写的做。
ENOENT, open '/mnt/avos/data/uluru-cloud-code/repos/cfe31dfea15a5a658a52e7dc0cec0530/config/global.json'

**Comment by wangxiao** [comment]
cc @sdjcw 云代码问题？

**Comment by jasondu** [comment]
解决了，应该是git的问题，谢谢，可以加一下你微信吗？
