### ISSUE TITLE
[ERROR] 当前目录没有任何应用信息，请使用：add <name> <app id> 关联应用。

### ISSUE THREAD

**Issue by wangyun122** [leancloud/LeanEngine-Full-Stack#29]
[ERROR] 当前目录没有任何应用信息，请使用：add <name> <app id> 关联应用。
在根目录输入avoscloud 出现这个错误。

**Comment by wangxiao** [comment]
因为是和 LeanEngine 绑定的，所以你需要先了解下如何使用 LeanEngine 
文档地址 https://leancloud.cn/docs/leanengine_guide-node.html
