### ISSUE TITLE
复杂项目怎么个框架？

### ISSUE THREAD

**Issue by longxianlin** [leancloud/LeanEngine-Full-Stack#32]
要部署的网站有前台，后台，移动html，还能提供api，还有云函数

**Comment by wangxiao** [comment]
后台指的是服务端代码吗？还是业务逻辑上的配置后台？

不考虑具体需求，肯定是要先服务端和前端（iOS、Android 和 Web 等）解耦合，之间通过 SDK 或者 API 来交互。LeanEngine-Full-Stack 考虑的方式是通过比较传统的自定义 REST Api 来解决的，server-module 中就是服务端代码，而 web-project 全是 Web 前端项目代码，完全独立构建，所以 web-project 可以换为 iOS-project 或 Android-project，当然如果是仍然是移动端的 Web 其实也是 Web，仍然可以使用 web-project，也可以类似 web-project-mobile、web-project-pc 之类的。

**Comment by wangxiao** [comment]
具体的还是阅读下 Blog 了解。 https://blog.leancloud.cn/3729/
