### ISSUE TITLE
LeanEngine-Full-Stack短时间会更新Angular 2吗？

### ISSUE THREAD

**Issue by bdqy** [leancloud/LeanEngine-Full-Stack#35]
Angular 2已经发布了，短时间内会更新吗？

**Comment by wangxiao** [comment]
短时间内不会。

还是偏向于比较保守的技术策略，Angular2 本身没有到正式版的状态，官方也强调了不要使用在开发环境中。其次是功能性并没有得到任何验证，所以暂时不会更新到 Angular2。
