### ISSUE TITLE
无法使用 async/await

### ISSUE THREAD

**Issue by filod** [leancloud/LeanEngine-Full-Stack#39]
去掉 async/await相关代码后，直接部署本项目，报错如下
```
[ERROR] /mnt/avos/data/uluru-cloud-code/repos/mn95md0datvcjdwf55mynqouofo7eqvz4tx1z0h59omxjb43/node_modules/babel-core/lib/transformation/file/index.js:556
[ERROR]       throw err;
[ERROR]             ^
[ERROR] SyntaxError: /mnt/avos/data/uluru-cloud-code/repos/mn95md0datvcjdwf55mynqouofo7eqvz4tx1z0h59omxjb43/server-modules/api-router.js: Unexpected token (30:27)
[ERROR]   28 | };
[ERROR]   29 |
[ERROR] > 30 | const testAsync = async () => {
[ERROR]      |                            ^
[ERROR]   31 |   const t = await f();
[ERROR]   32 |   console.log(t);
[ERROR]   33 | };
```

之前猜测可能是 .babelrc 被干掉了，于是用 require hook 替换，发现还是不行。（本地执行完全没问题）

**Comment by filod** [comment]
@wangxiao any thoughts?

**Comment by wangxiao** [comment]
看报错是箭头函数就不支持了，新版云引擎已经发布，你可以在你的 package.json 文件中选择使用 Nodejs 4.x 版本。

```
{
  "name": "Demo",
  "version": "1.0.0",
  "main": "server.js",
  "scripts": {
    "start": "node ./server.js"
  },
  "license": "MIT",
  "dependencies": {
    "babel-core": "^6.1.2",
    "babel-polyfill": "^6.0.16",
    "babel-preset-stage-3": "^6.1.2",
    "body-parser": "1.12.3",
    "connect-busboy": "0.0.2",
    "cookie-parser": "^1.3.5",
    "ejs": "2.3.1",
    "express": "4.12.3",
    "leanengine": "^0.2.0",
    "leanengine-sniper": "^0.3.2",
    "mailgun-js": "^0.7.6",
    "moment": "^2.10.6",
    "jssha": "^1.5.0"
  },
  "engines": {
    "node": "4.x"
  }
}
```

**Comment by filod** [comment]
@wangxiao 刚试了一下，依然不行
![image](https://cloud.githubusercontent.com/assets/679897/13624024/bb8b2e3c-e5e5-11e5-97bc-05790cadf668.png)
这次貌似所有的 ES6 代码都无法执行了

**Comment by wangxiao** [comment]
最近写的应用基本都是 ES6 的了，就在线上运行着。
从现象来看，babel 应该没有启动。
你的应用在本地通过 avoscloud 运行是正常的么？babel 都正常启动了吗？

**Comment by filod** [comment]
本地用 lean up 没有问题（我自己的项目和 LeanEngine-Full-Stack均没有问题）

**Comment by wangxiao** [comment]
咦？就是说你自己的项目和 LeanEngine-Full-Stack 本地和部署均没有问题？
但是只有你现在这个项目部署上去有问题？

如果是这种情况，还是看下配置上是否有问题，比如 package.json、babel 等配置，另外考虑是否 ignore 了某些重要文件。

**Comment by filod** [comment]
LeanEngine-Full-Stack 和我的项目本地都能运行，LeanEngine-Full-Stack 一行代码未改, 依然无法部署， lean-cli 也升级到最新版。

babel 通过 .babelrc 和 require hook 两种方式都无法正常工作（require hook 还没在新引擎上试过）。

没有配置 .leanengineignore,  .gitignore 应该不影响吧（而且配置也正常）？

难道是我的 appid 出了问题？

**Comment by filod** [comment]
刚测试了一下，使用 LeanEngine-Full-Stack 和一个全新的测试应用， 依然报错.

然后我重新注册了一个 leancloud 帐号，然后部署同样的项目，依然报错……

:scream:

**Comment by filod** [comment]
ps, 我本地：

node: v4.1.2
npm: 2.14.15
lean-cli: 0.11.0

**Comment by filod** [comment]
PPS,  我换了台机器进行部署，依然不行

**Comment by filod** [comment]
PPPS, 我已经找到原因了 ，是 lean-cli 在打包的时候没有将 dot file 打包进去，

在 node 4 下，删除了 babelrc, 通过 hook 方式加载已经没问题了

**Comment by wangxiao** [comment]
好的，我转给新版命令工具的同事。

**Comment by filod** [comment]
PS, 这个同样受到 https://github.com/leancloud/leanengine-node-sdk/issues/14  问题的影响
