### ISSUE TITLE
这个项目用webpack了?

### ISSUE THREAD

**Issue by mqliutie** [leancloud/LeanEngine-Full-Stack#41]
我看 `node_modules `里面有 `webpack` , 不过没看到哪里用到啊
这个项目是怎么处理图片的呢?我看这个例子中没有另外引图片 , `build `以后 `public` 下面也没有 `images` 文件夹

**Comment by wangxiao** [comment]
所有构建过程在 /web-project/gulp 目录中，比如 webpack 主要用在 script 的处理中 https://github.com/leancloud/LeanEngine-Full-Stack/blob/master/web-project/gulp/scripts.js
